config/routes.rb
Rails.application.routes.draw do
  
  devise_for :userms
  get 'destroy_session/index'

  get 'appuser/index'

  root 'my_home#index'
  #Show Login Page
  get 'ruchi/showLogin'

  #Show New Sign UP page
  get 'ruchi/signup'

  #get 'editProfile' , to: 'devise/registrations#edit'
  

  get 'article/index'

  resources :users
  #get 'ruchi/index'
  get "ruchi/index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "ruchi/register"
  get "ruchi/ViewUser"
  # Ajax Call 
  post "ruchi/JsonTest"
  # Show Edit Page
  get "ruchi/editm"
  #Login View
  post "ruchi/login"
  #Destroy User Session
  get "appuser/destroy"

  get "appuser/logout"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/registration.rb
class Registration < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/userm.rb
class Userm < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/appuser_controller.rb
class AppuserController < ApplicationController
  protect_from_forgery
  layout 'appuserLayout'


  def index
    #byebug
    
    dearUser = User.where(id: params[:user]).first
    #p "mY PARAMETER==========" +params[:user].to_s

    session[:ravi]=dearUser.id

    if(session[:ravi]!=nil)
      @title=dearUser.fname.to_s  
      @id=dearUser.id  
    else
      redirect_to '/'
    end
  end

  def destroy
    #byebug
    reset_session
    session[:ravi] = nil
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    redirect_to "/article/index"
  end

  def logout
    #cbyebug
    # if(session[:ravi]==nil)
    #   redirect_to "/appuser/logout"
    # else

    #end
  end


end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
 
  def index
    # if(session[:ravi]==nil)
    #   redirect_to "/"
    # end
  end
end

app/controllers/my_home_controller.rb
class MyHomeController < ApplicationController
  layout "MyLayout"
  def index
    @title = "home"
  end
end

app/controllers/ruchi_controller.rb
class RuchiController < ApplicationController
  protect_from_forgery
  #skip_before_action :verify_authenticity_token, if: :json_request?
  #respond_to :js, :json, :html
  layout 'MyLayout'
  def index
    @title = "Sign up"
  end

  def showLogin
    @title = "Sign In"
  end

  #SignUP page
  def signup
    @title = "Sign up"
  end

  def register

    tpass= user_params[:pass]
    trepass= user_params[:repass]  
    if(tpass == trepass)
      
      reg=User.new(user_params)

      if reg.save
        # p reg.id
        redirect_to '/ruchi/showLogin'
      else
        flash[:register_error]=reg.errors.full_messages
      end
    else
      redirect_to '/ruchi/index?error=5'
      # p "incorrect password"
      # p ">>>>>>>>>>>>>>>>>>>>>>>>"
    end
    
  end

 
  def JsonTest
    #byebug
    @test=User.all
    respond_to do |format|
      format.json {render json:@test}
    end
    #respond_with @test
    #render :json => @test
    
  end


  #Login Functionality
  def login
   
    #byebug
    txtemail = f_params[:email]
    txtpass = f_params[:pass]
    #p 'User ID '+txtemail
    dearUser = User.where(email: txtemail).first
    #p @dearUser[:id]

    
    if(txtpass == dearUser.pass)
      session[:ravi]=dearUser.id
      session[:user_email]=dearUser.email
    #  p "--------------ruchi controller---------------"+ session[:ravi].to_s
      userid= dearUser.id

      redirect_to "/appuser/index?user="+userid.to_s

    else
      redirect_to '/users/showLogin?error=1'
    end

  end 



  def ViewUser
    @title = "User"

    @test=User.all

  end

  

  private
    def user_params
      params.require(:user).permit(:fname, :lname,:email,:pass, :repass)
      
    end
    def f_params
      params.require(:f).permit(:email,:pass)
    end
end

app/controllers/userm_controller.rb
class UsermController < ApplicationController
	layout "MyLayout"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :pass)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appuser_helper.rb
module AppuserHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/artivle_helper.rb
module ArtivleHelper
end

app/helpers/destroy_session_helper.rb
module DestroySessionHelper
end

app/helpers/my_home_helper.rb
module MyHomeHelper
end

app/helpers/ruby_user_helper.rb
module RubyUserHelper
end

app/helpers/ruchi_helper.rb
module RuchiHelper
end

app/helpers/userm_helper.rb
module UsermHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/MyLayout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Ruby App | <%=@title%></title>
  <%= csrf_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application"  %>
</head>
<body>

        <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Das Vidania</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
              <li style="display:none"><a href="/ruchi/index">Sign-Up</a></li>
              <li><a href="/ruchi/ViewUser">Users</a></li>
              <%# <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li> %>
            </ul>
            <ul class="nav navbar-nav navbar-right">

              <% if userm_signed_in? %>


            <li>
              <%=link_to "Sign Out", destroy_userm_session_path , method:"DELETE" %>
            </li>

             <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">

                <li><%= link_to "Profile", '#' %></li>

                <li><%= link_to "Edit Profile",edit_userm_registration_path, method:"get" %></li>

            </ul>
          </li>


              <% else %>
            <li>
            <!--   <a href="/ruchi/index">Sign-Up</a> -->
            <%= link_to "Sign-Up" ,new_userm_registration_path,method:"GET" %>
            </li>
            <li>

            <!--   <a href="/ruchi/showLogin">Sign-In</a> -->

                <%= link_to "Sign In" , new_userm_session_path ,method:"GET" %>

            </li>
          
          <% end %>
           
              <%# <li><a href="../navbar-static-top/">Static top</a></li> %>
              <%# <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li> %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
        </nav>


      <section class="container">

<br><br>

             <div id="notice" style="display: none" class="alert alert-info"><%= notice %></div>

             <div id="alert"  style="display: none" class="alert alert-warning"><%= alert %></div>


            <%= yield %>

      </section>


      <script type="text/javascript">
        
        window.onload=function(){
          var ntc="<%= notice %>"
          //console.log(ntc)
          //alert("NTC"+ntc)
          
           if(ntc=="")
           {

            $("#notice").hide();

           } 
           else
           {
              $("#notice").show();

           }
           var a="<%= alert %>"
           //console.log(a)
           //alert(a)
           if(a=="")
           {
              $("#alert").hide();
           }
           else
           {
            $("#alert").show();
           }


        }

      </script>
   </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/appuserLayout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Welcome - <%=@title%></title>
  <%= csrf_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
  window.onload =function () {

    var userSession=<%=session[:ravi]%>
    //alert(userSession)
    if(userSession=="" || userSession==null)
    {

      location.href="/"
    }
    
  }
  </script>
 
</head>
<body>

        <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/appuser/index?user=<%=@id%>">Das Vidania</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/appuser/profile">Profile</a></li>
              <%# <li style="display:none"><a href="/ruchi/index">Sign-Up</a></li>
              <li><a href="/ruchi/ViewUser">Users</a></li> %>
              <%# <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li> %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            
            <li><a href="/appuser/destroy">SignOut</a></li>
           
              <%# <li><a href="../navbar-static-top/">Static top</a></li> %>
              <%# <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li> %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
        </nav>


      <section class="container">


            <%= yield %>

      </section>
   </body>

</html>